/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.4
 * source: wrapper.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./stats/api";
import * as dependency_2 from "./user/api";
import * as dependency_3 from "./courses/api";
import * as dependency_4 from "./content/api";
import * as pb_1 from "google-protobuf";
export namespace messages {
    export enum ErrorCode {
        GENERAL = 0,
        NOT_FOUND = 1
    }
    export class Error extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            error_code?: ErrorCode;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("error_code" in data && data.error_code != undefined) {
                    this.error_code = data.error_code;
                }
            }
        }
        get error_code() {
            return pb_1.Message.getFieldWithDefault(this, 1, ErrorCode.GENERAL) as ErrorCode;
        }
        set error_code(value: ErrorCode) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            error_code?: ErrorCode;
        }): Error {
            const message = new Error({});
            if (data.error_code != null) {
                message.error_code = data.error_code;
            }
            return message;
        }
        toObject() {
            const data: {
                error_code?: ErrorCode;
            } = {};
            if (this.error_code != null) {
                data.error_code = this.error_code;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.error_code != ErrorCode.GENERAL)
                writer.writeEnum(1, this.error_code);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Error {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Error();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.error_code = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Error {
            return Error.deserialize(bytes);
        }
    }
    export class Wrapper extends pb_1.Message {
        #one_of_decls: number[][] = [[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], [1]];
        constructor(data?: any[] | ({} & (({
            error_response?: Error;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: dependency_1.messages.GetLatestStatsRequest;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: dependency_1.messages.GetLatestStatsResponse;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: dependency_2.messages.GetUserRequest;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: dependency_2.messages.GetUserResponse;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: dependency_2.messages.UpdateDiscordUserRequest;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: dependency_2.messages.UpdateDiscordUserResponse;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: dependency_3.messages.GetCoursesTeasersRequest;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: dependency_3.messages.GetCoursesTeasersResponse;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: dependency_3.messages.GetCourseRequest;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: dependency_3.messages.GetCourseResponse;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: dependency_4.messages.GetPageRequest;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: dependency_4.messages.GetPageResponse;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: dependency_4.messages.GetPostsTeasersRequest;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: dependency_4.messages.GetPostsTeasersResponse;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: dependency_4.messages.GetPostRequest;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: dependency_4.messages.GetPostResponse;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: dependency_4.messages.GetCategoriesTeasersRequest;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: dependency_4.messages.GetCategoriesTeasersResponse;
            get_category_request?: never;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: dependency_4.messages.GetCategoryRequest;
            get_category_response?: never;
        } | {
            error_response?: never;
            get_latest_stats_request?: never;
            get_latest_stats_response?: never;
            get_user_request?: never;
            get_user_response?: never;
            update_discord_user_request?: never;
            update_discord_user_response?: never;
            get_courses_teasers_request?: never;
            get_courses_teasers_response?: never;
            get_course_request?: never;
            get_course_response?: never;
            get_page_request?: never;
            get_page_response?: never;
            get_posts_teasers_request?: never;
            get_posts_teasers_response?: never;
            get_post_request?: never;
            get_post_response?: never;
            get_categories_teasers_request?: never;
            get_categories_teasers_response?: never;
            get_category_request?: never;
            get_category_response?: dependency_4.messages.GetCategoryResponse;
        }) | ({
            api_token?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("api_token" in data && data.api_token != undefined) {
                    this.api_token = data.api_token;
                }
                if ("error_response" in data && data.error_response != undefined) {
                    this.error_response = data.error_response;
                }
                if ("get_latest_stats_request" in data && data.get_latest_stats_request != undefined) {
                    this.get_latest_stats_request = data.get_latest_stats_request;
                }
                if ("get_latest_stats_response" in data && data.get_latest_stats_response != undefined) {
                    this.get_latest_stats_response = data.get_latest_stats_response;
                }
                if ("get_user_request" in data && data.get_user_request != undefined) {
                    this.get_user_request = data.get_user_request;
                }
                if ("get_user_response" in data && data.get_user_response != undefined) {
                    this.get_user_response = data.get_user_response;
                }
                if ("update_discord_user_request" in data && data.update_discord_user_request != undefined) {
                    this.update_discord_user_request = data.update_discord_user_request;
                }
                if ("update_discord_user_response" in data && data.update_discord_user_response != undefined) {
                    this.update_discord_user_response = data.update_discord_user_response;
                }
                if ("get_courses_teasers_request" in data && data.get_courses_teasers_request != undefined) {
                    this.get_courses_teasers_request = data.get_courses_teasers_request;
                }
                if ("get_courses_teasers_response" in data && data.get_courses_teasers_response != undefined) {
                    this.get_courses_teasers_response = data.get_courses_teasers_response;
                }
                if ("get_course_request" in data && data.get_course_request != undefined) {
                    this.get_course_request = data.get_course_request;
                }
                if ("get_course_response" in data && data.get_course_response != undefined) {
                    this.get_course_response = data.get_course_response;
                }
                if ("get_page_request" in data && data.get_page_request != undefined) {
                    this.get_page_request = data.get_page_request;
                }
                if ("get_page_response" in data && data.get_page_response != undefined) {
                    this.get_page_response = data.get_page_response;
                }
                if ("get_posts_teasers_request" in data && data.get_posts_teasers_request != undefined) {
                    this.get_posts_teasers_request = data.get_posts_teasers_request;
                }
                if ("get_posts_teasers_response" in data && data.get_posts_teasers_response != undefined) {
                    this.get_posts_teasers_response = data.get_posts_teasers_response;
                }
                if ("get_post_request" in data && data.get_post_request != undefined) {
                    this.get_post_request = data.get_post_request;
                }
                if ("get_post_response" in data && data.get_post_response != undefined) {
                    this.get_post_response = data.get_post_response;
                }
                if ("get_categories_teasers_request" in data && data.get_categories_teasers_request != undefined) {
                    this.get_categories_teasers_request = data.get_categories_teasers_request;
                }
                if ("get_categories_teasers_response" in data && data.get_categories_teasers_response != undefined) {
                    this.get_categories_teasers_response = data.get_categories_teasers_response;
                }
                if ("get_category_request" in data && data.get_category_request != undefined) {
                    this.get_category_request = data.get_category_request;
                }
                if ("get_category_response" in data && data.get_category_response != undefined) {
                    this.get_category_response = data.get_category_response;
                }
            }
        }
        get api_token() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set api_token(value: string) {
            pb_1.Message.setOneofField(this, 1, this.#one_of_decls[1], value);
        }
        get has_api_token() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get error_response() {
            return pb_1.Message.getWrapperField(this, Error, 2) as Error;
        }
        set error_response(value: Error) {
            pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
        }
        get has_error_response() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get get_latest_stats_request() {
            return pb_1.Message.getWrapperField(this, dependency_1.messages.GetLatestStatsRequest, 3) as dependency_1.messages.GetLatestStatsRequest;
        }
        set get_latest_stats_request(value: dependency_1.messages.GetLatestStatsRequest) {
            pb_1.Message.setOneofWrapperField(this, 3, this.#one_of_decls[0], value);
        }
        get has_get_latest_stats_request() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get get_latest_stats_response() {
            return pb_1.Message.getWrapperField(this, dependency_1.messages.GetLatestStatsResponse, 4) as dependency_1.messages.GetLatestStatsResponse;
        }
        set get_latest_stats_response(value: dependency_1.messages.GetLatestStatsResponse) {
            pb_1.Message.setOneofWrapperField(this, 4, this.#one_of_decls[0], value);
        }
        get has_get_latest_stats_response() {
            return pb_1.Message.getField(this, 4) != null;
        }
        get get_user_request() {
            return pb_1.Message.getWrapperField(this, dependency_2.messages.GetUserRequest, 5) as dependency_2.messages.GetUserRequest;
        }
        set get_user_request(value: dependency_2.messages.GetUserRequest) {
            pb_1.Message.setOneofWrapperField(this, 5, this.#one_of_decls[0], value);
        }
        get has_get_user_request() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get get_user_response() {
            return pb_1.Message.getWrapperField(this, dependency_2.messages.GetUserResponse, 6) as dependency_2.messages.GetUserResponse;
        }
        set get_user_response(value: dependency_2.messages.GetUserResponse) {
            pb_1.Message.setOneofWrapperField(this, 6, this.#one_of_decls[0], value);
        }
        get has_get_user_response() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get update_discord_user_request() {
            return pb_1.Message.getWrapperField(this, dependency_2.messages.UpdateDiscordUserRequest, 7) as dependency_2.messages.UpdateDiscordUserRequest;
        }
        set update_discord_user_request(value: dependency_2.messages.UpdateDiscordUserRequest) {
            pb_1.Message.setOneofWrapperField(this, 7, this.#one_of_decls[0], value);
        }
        get has_update_discord_user_request() {
            return pb_1.Message.getField(this, 7) != null;
        }
        get update_discord_user_response() {
            return pb_1.Message.getWrapperField(this, dependency_2.messages.UpdateDiscordUserResponse, 8) as dependency_2.messages.UpdateDiscordUserResponse;
        }
        set update_discord_user_response(value: dependency_2.messages.UpdateDiscordUserResponse) {
            pb_1.Message.setOneofWrapperField(this, 8, this.#one_of_decls[0], value);
        }
        get has_update_discord_user_response() {
            return pb_1.Message.getField(this, 8) != null;
        }
        get get_courses_teasers_request() {
            return pb_1.Message.getWrapperField(this, dependency_3.messages.GetCoursesTeasersRequest, 9) as dependency_3.messages.GetCoursesTeasersRequest;
        }
        set get_courses_teasers_request(value: dependency_3.messages.GetCoursesTeasersRequest) {
            pb_1.Message.setOneofWrapperField(this, 9, this.#one_of_decls[0], value);
        }
        get has_get_courses_teasers_request() {
            return pb_1.Message.getField(this, 9) != null;
        }
        get get_courses_teasers_response() {
            return pb_1.Message.getWrapperField(this, dependency_3.messages.GetCoursesTeasersResponse, 10) as dependency_3.messages.GetCoursesTeasersResponse;
        }
        set get_courses_teasers_response(value: dependency_3.messages.GetCoursesTeasersResponse) {
            pb_1.Message.setOneofWrapperField(this, 10, this.#one_of_decls[0], value);
        }
        get has_get_courses_teasers_response() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get get_course_request() {
            return pb_1.Message.getWrapperField(this, dependency_3.messages.GetCourseRequest, 11) as dependency_3.messages.GetCourseRequest;
        }
        set get_course_request(value: dependency_3.messages.GetCourseRequest) {
            pb_1.Message.setOneofWrapperField(this, 11, this.#one_of_decls[0], value);
        }
        get has_get_course_request() {
            return pb_1.Message.getField(this, 11) != null;
        }
        get get_course_response() {
            return pb_1.Message.getWrapperField(this, dependency_3.messages.GetCourseResponse, 12) as dependency_3.messages.GetCourseResponse;
        }
        set get_course_response(value: dependency_3.messages.GetCourseResponse) {
            pb_1.Message.setOneofWrapperField(this, 12, this.#one_of_decls[0], value);
        }
        get has_get_course_response() {
            return pb_1.Message.getField(this, 12) != null;
        }
        get get_page_request() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetPageRequest, 13) as dependency_4.messages.GetPageRequest;
        }
        set get_page_request(value: dependency_4.messages.GetPageRequest) {
            pb_1.Message.setOneofWrapperField(this, 13, this.#one_of_decls[0], value);
        }
        get has_get_page_request() {
            return pb_1.Message.getField(this, 13) != null;
        }
        get get_page_response() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetPageResponse, 14) as dependency_4.messages.GetPageResponse;
        }
        set get_page_response(value: dependency_4.messages.GetPageResponse) {
            pb_1.Message.setOneofWrapperField(this, 14, this.#one_of_decls[0], value);
        }
        get has_get_page_response() {
            return pb_1.Message.getField(this, 14) != null;
        }
        get get_posts_teasers_request() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetPostsTeasersRequest, 15) as dependency_4.messages.GetPostsTeasersRequest;
        }
        set get_posts_teasers_request(value: dependency_4.messages.GetPostsTeasersRequest) {
            pb_1.Message.setOneofWrapperField(this, 15, this.#one_of_decls[0], value);
        }
        get has_get_posts_teasers_request() {
            return pb_1.Message.getField(this, 15) != null;
        }
        get get_posts_teasers_response() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetPostsTeasersResponse, 16) as dependency_4.messages.GetPostsTeasersResponse;
        }
        set get_posts_teasers_response(value: dependency_4.messages.GetPostsTeasersResponse) {
            pb_1.Message.setOneofWrapperField(this, 16, this.#one_of_decls[0], value);
        }
        get has_get_posts_teasers_response() {
            return pb_1.Message.getField(this, 16) != null;
        }
        get get_post_request() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetPostRequest, 17) as dependency_4.messages.GetPostRequest;
        }
        set get_post_request(value: dependency_4.messages.GetPostRequest) {
            pb_1.Message.setOneofWrapperField(this, 17, this.#one_of_decls[0], value);
        }
        get has_get_post_request() {
            return pb_1.Message.getField(this, 17) != null;
        }
        get get_post_response() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetPostResponse, 18) as dependency_4.messages.GetPostResponse;
        }
        set get_post_response(value: dependency_4.messages.GetPostResponse) {
            pb_1.Message.setOneofWrapperField(this, 18, this.#one_of_decls[0], value);
        }
        get has_get_post_response() {
            return pb_1.Message.getField(this, 18) != null;
        }
        get get_categories_teasers_request() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetCategoriesTeasersRequest, 19) as dependency_4.messages.GetCategoriesTeasersRequest;
        }
        set get_categories_teasers_request(value: dependency_4.messages.GetCategoriesTeasersRequest) {
            pb_1.Message.setOneofWrapperField(this, 19, this.#one_of_decls[0], value);
        }
        get has_get_categories_teasers_request() {
            return pb_1.Message.getField(this, 19) != null;
        }
        get get_categories_teasers_response() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetCategoriesTeasersResponse, 20) as dependency_4.messages.GetCategoriesTeasersResponse;
        }
        set get_categories_teasers_response(value: dependency_4.messages.GetCategoriesTeasersResponse) {
            pb_1.Message.setOneofWrapperField(this, 20, this.#one_of_decls[0], value);
        }
        get has_get_categories_teasers_response() {
            return pb_1.Message.getField(this, 20) != null;
        }
        get get_category_request() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetCategoryRequest, 21) as dependency_4.messages.GetCategoryRequest;
        }
        set get_category_request(value: dependency_4.messages.GetCategoryRequest) {
            pb_1.Message.setOneofWrapperField(this, 21, this.#one_of_decls[0], value);
        }
        get has_get_category_request() {
            return pb_1.Message.getField(this, 21) != null;
        }
        get get_category_response() {
            return pb_1.Message.getWrapperField(this, dependency_4.messages.GetCategoryResponse, 22) as dependency_4.messages.GetCategoryResponse;
        }
        set get_category_response(value: dependency_4.messages.GetCategoryResponse) {
            pb_1.Message.setOneofWrapperField(this, 22, this.#one_of_decls[0], value);
        }
        get has_get_category_response() {
            return pb_1.Message.getField(this, 22) != null;
        }
        get message() {
            const cases: {
                [index: number]: "none" | "error_response" | "get_latest_stats_request" | "get_latest_stats_response" | "get_user_request" | "get_user_response" | "update_discord_user_request" | "update_discord_user_response" | "get_courses_teasers_request" | "get_courses_teasers_response" | "get_course_request" | "get_course_response" | "get_page_request" | "get_page_response" | "get_posts_teasers_request" | "get_posts_teasers_response" | "get_post_request" | "get_post_response" | "get_categories_teasers_request" | "get_categories_teasers_response" | "get_category_request" | "get_category_response";
            } = {
                0: "none",
                2: "error_response",
                3: "get_latest_stats_request",
                4: "get_latest_stats_response",
                5: "get_user_request",
                6: "get_user_response",
                7: "update_discord_user_request",
                8: "update_discord_user_response",
                9: "get_courses_teasers_request",
                10: "get_courses_teasers_response",
                11: "get_course_request",
                12: "get_course_response",
                13: "get_page_request",
                14: "get_page_response",
                15: "get_posts_teasers_request",
                16: "get_posts_teasers_response",
                17: "get_post_request",
                18: "get_post_response",
                19: "get_categories_teasers_request",
                20: "get_categories_teasers_response",
                21: "get_category_request",
                22: "get_category_response"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])];
        }
        get _api_token() {
            const cases: {
                [index: number]: "none" | "api_token";
            } = {
                0: "none",
                1: "api_token"
            };
            return cases[pb_1.Message.computeOneofCase(this, [1])];
        }
        static fromObject(data: {
            api_token?: string;
            error_response?: ReturnType<typeof Error.prototype.toObject>;
            get_latest_stats_request?: ReturnType<typeof dependency_1.messages.GetLatestStatsRequest.prototype.toObject>;
            get_latest_stats_response?: ReturnType<typeof dependency_1.messages.GetLatestStatsResponse.prototype.toObject>;
            get_user_request?: ReturnType<typeof dependency_2.messages.GetUserRequest.prototype.toObject>;
            get_user_response?: ReturnType<typeof dependency_2.messages.GetUserResponse.prototype.toObject>;
            update_discord_user_request?: ReturnType<typeof dependency_2.messages.UpdateDiscordUserRequest.prototype.toObject>;
            update_discord_user_response?: ReturnType<typeof dependency_2.messages.UpdateDiscordUserResponse.prototype.toObject>;
            get_courses_teasers_request?: ReturnType<typeof dependency_3.messages.GetCoursesTeasersRequest.prototype.toObject>;
            get_courses_teasers_response?: ReturnType<typeof dependency_3.messages.GetCoursesTeasersResponse.prototype.toObject>;
            get_course_request?: ReturnType<typeof dependency_3.messages.GetCourseRequest.prototype.toObject>;
            get_course_response?: ReturnType<typeof dependency_3.messages.GetCourseResponse.prototype.toObject>;
            get_page_request?: ReturnType<typeof dependency_4.messages.GetPageRequest.prototype.toObject>;
            get_page_response?: ReturnType<typeof dependency_4.messages.GetPageResponse.prototype.toObject>;
            get_posts_teasers_request?: ReturnType<typeof dependency_4.messages.GetPostsTeasersRequest.prototype.toObject>;
            get_posts_teasers_response?: ReturnType<typeof dependency_4.messages.GetPostsTeasersResponse.prototype.toObject>;
            get_post_request?: ReturnType<typeof dependency_4.messages.GetPostRequest.prototype.toObject>;
            get_post_response?: ReturnType<typeof dependency_4.messages.GetPostResponse.prototype.toObject>;
            get_categories_teasers_request?: ReturnType<typeof dependency_4.messages.GetCategoriesTeasersRequest.prototype.toObject>;
            get_categories_teasers_response?: ReturnType<typeof dependency_4.messages.GetCategoriesTeasersResponse.prototype.toObject>;
            get_category_request?: ReturnType<typeof dependency_4.messages.GetCategoryRequest.prototype.toObject>;
            get_category_response?: ReturnType<typeof dependency_4.messages.GetCategoryResponse.prototype.toObject>;
        }): Wrapper {
            const message = new Wrapper({});
            if (data.api_token != null) {
                message.api_token = data.api_token;
            }
            if (data.error_response != null) {
                message.error_response = Error.fromObject(data.error_response);
            }
            if (data.get_latest_stats_request != null) {
                message.get_latest_stats_request = dependency_1.messages.GetLatestStatsRequest.fromObject(data.get_latest_stats_request);
            }
            if (data.get_latest_stats_response != null) {
                message.get_latest_stats_response = dependency_1.messages.GetLatestStatsResponse.fromObject(data.get_latest_stats_response);
            }
            if (data.get_user_request != null) {
                message.get_user_request = dependency_2.messages.GetUserRequest.fromObject(data.get_user_request);
            }
            if (data.get_user_response != null) {
                message.get_user_response = dependency_2.messages.GetUserResponse.fromObject(data.get_user_response);
            }
            if (data.update_discord_user_request != null) {
                message.update_discord_user_request = dependency_2.messages.UpdateDiscordUserRequest.fromObject(data.update_discord_user_request);
            }
            if (data.update_discord_user_response != null) {
                message.update_discord_user_response = dependency_2.messages.UpdateDiscordUserResponse.fromObject(data.update_discord_user_response);
            }
            if (data.get_courses_teasers_request != null) {
                message.get_courses_teasers_request = dependency_3.messages.GetCoursesTeasersRequest.fromObject(data.get_courses_teasers_request);
            }
            if (data.get_courses_teasers_response != null) {
                message.get_courses_teasers_response = dependency_3.messages.GetCoursesTeasersResponse.fromObject(data.get_courses_teasers_response);
            }
            if (data.get_course_request != null) {
                message.get_course_request = dependency_3.messages.GetCourseRequest.fromObject(data.get_course_request);
            }
            if (data.get_course_response != null) {
                message.get_course_response = dependency_3.messages.GetCourseResponse.fromObject(data.get_course_response);
            }
            if (data.get_page_request != null) {
                message.get_page_request = dependency_4.messages.GetPageRequest.fromObject(data.get_page_request);
            }
            if (data.get_page_response != null) {
                message.get_page_response = dependency_4.messages.GetPageResponse.fromObject(data.get_page_response);
            }
            if (data.get_posts_teasers_request != null) {
                message.get_posts_teasers_request = dependency_4.messages.GetPostsTeasersRequest.fromObject(data.get_posts_teasers_request);
            }
            if (data.get_posts_teasers_response != null) {
                message.get_posts_teasers_response = dependency_4.messages.GetPostsTeasersResponse.fromObject(data.get_posts_teasers_response);
            }
            if (data.get_post_request != null) {
                message.get_post_request = dependency_4.messages.GetPostRequest.fromObject(data.get_post_request);
            }
            if (data.get_post_response != null) {
                message.get_post_response = dependency_4.messages.GetPostResponse.fromObject(data.get_post_response);
            }
            if (data.get_categories_teasers_request != null) {
                message.get_categories_teasers_request = dependency_4.messages.GetCategoriesTeasersRequest.fromObject(data.get_categories_teasers_request);
            }
            if (data.get_categories_teasers_response != null) {
                message.get_categories_teasers_response = dependency_4.messages.GetCategoriesTeasersResponse.fromObject(data.get_categories_teasers_response);
            }
            if (data.get_category_request != null) {
                message.get_category_request = dependency_4.messages.GetCategoryRequest.fromObject(data.get_category_request);
            }
            if (data.get_category_response != null) {
                message.get_category_response = dependency_4.messages.GetCategoryResponse.fromObject(data.get_category_response);
            }
            return message;
        }
        toObject() {
            const data: {
                api_token?: string;
                error_response?: ReturnType<typeof Error.prototype.toObject>;
                get_latest_stats_request?: ReturnType<typeof dependency_1.messages.GetLatestStatsRequest.prototype.toObject>;
                get_latest_stats_response?: ReturnType<typeof dependency_1.messages.GetLatestStatsResponse.prototype.toObject>;
                get_user_request?: ReturnType<typeof dependency_2.messages.GetUserRequest.prototype.toObject>;
                get_user_response?: ReturnType<typeof dependency_2.messages.GetUserResponse.prototype.toObject>;
                update_discord_user_request?: ReturnType<typeof dependency_2.messages.UpdateDiscordUserRequest.prototype.toObject>;
                update_discord_user_response?: ReturnType<typeof dependency_2.messages.UpdateDiscordUserResponse.prototype.toObject>;
                get_courses_teasers_request?: ReturnType<typeof dependency_3.messages.GetCoursesTeasersRequest.prototype.toObject>;
                get_courses_teasers_response?: ReturnType<typeof dependency_3.messages.GetCoursesTeasersResponse.prototype.toObject>;
                get_course_request?: ReturnType<typeof dependency_3.messages.GetCourseRequest.prototype.toObject>;
                get_course_response?: ReturnType<typeof dependency_3.messages.GetCourseResponse.prototype.toObject>;
                get_page_request?: ReturnType<typeof dependency_4.messages.GetPageRequest.prototype.toObject>;
                get_page_response?: ReturnType<typeof dependency_4.messages.GetPageResponse.prototype.toObject>;
                get_posts_teasers_request?: ReturnType<typeof dependency_4.messages.GetPostsTeasersRequest.prototype.toObject>;
                get_posts_teasers_response?: ReturnType<typeof dependency_4.messages.GetPostsTeasersResponse.prototype.toObject>;
                get_post_request?: ReturnType<typeof dependency_4.messages.GetPostRequest.prototype.toObject>;
                get_post_response?: ReturnType<typeof dependency_4.messages.GetPostResponse.prototype.toObject>;
                get_categories_teasers_request?: ReturnType<typeof dependency_4.messages.GetCategoriesTeasersRequest.prototype.toObject>;
                get_categories_teasers_response?: ReturnType<typeof dependency_4.messages.GetCategoriesTeasersResponse.prototype.toObject>;
                get_category_request?: ReturnType<typeof dependency_4.messages.GetCategoryRequest.prototype.toObject>;
                get_category_response?: ReturnType<typeof dependency_4.messages.GetCategoryResponse.prototype.toObject>;
            } = {};
            if (this.api_token != null) {
                data.api_token = this.api_token;
            }
            if (this.error_response != null) {
                data.error_response = this.error_response.toObject();
            }
            if (this.get_latest_stats_request != null) {
                data.get_latest_stats_request = this.get_latest_stats_request.toObject();
            }
            if (this.get_latest_stats_response != null) {
                data.get_latest_stats_response = this.get_latest_stats_response.toObject();
            }
            if (this.get_user_request != null) {
                data.get_user_request = this.get_user_request.toObject();
            }
            if (this.get_user_response != null) {
                data.get_user_response = this.get_user_response.toObject();
            }
            if (this.update_discord_user_request != null) {
                data.update_discord_user_request = this.update_discord_user_request.toObject();
            }
            if (this.update_discord_user_response != null) {
                data.update_discord_user_response = this.update_discord_user_response.toObject();
            }
            if (this.get_courses_teasers_request != null) {
                data.get_courses_teasers_request = this.get_courses_teasers_request.toObject();
            }
            if (this.get_courses_teasers_response != null) {
                data.get_courses_teasers_response = this.get_courses_teasers_response.toObject();
            }
            if (this.get_course_request != null) {
                data.get_course_request = this.get_course_request.toObject();
            }
            if (this.get_course_response != null) {
                data.get_course_response = this.get_course_response.toObject();
            }
            if (this.get_page_request != null) {
                data.get_page_request = this.get_page_request.toObject();
            }
            if (this.get_page_response != null) {
                data.get_page_response = this.get_page_response.toObject();
            }
            if (this.get_posts_teasers_request != null) {
                data.get_posts_teasers_request = this.get_posts_teasers_request.toObject();
            }
            if (this.get_posts_teasers_response != null) {
                data.get_posts_teasers_response = this.get_posts_teasers_response.toObject();
            }
            if (this.get_post_request != null) {
                data.get_post_request = this.get_post_request.toObject();
            }
            if (this.get_post_response != null) {
                data.get_post_response = this.get_post_response.toObject();
            }
            if (this.get_categories_teasers_request != null) {
                data.get_categories_teasers_request = this.get_categories_teasers_request.toObject();
            }
            if (this.get_categories_teasers_response != null) {
                data.get_categories_teasers_response = this.get_categories_teasers_response.toObject();
            }
            if (this.get_category_request != null) {
                data.get_category_request = this.get_category_request.toObject();
            }
            if (this.get_category_response != null) {
                data.get_category_response = this.get_category_response.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_api_token)
                writer.writeString(1, this.api_token);
            if (this.has_error_response)
                writer.writeMessage(2, this.error_response, () => this.error_response.serialize(writer));
            if (this.has_get_latest_stats_request)
                writer.writeMessage(3, this.get_latest_stats_request, () => this.get_latest_stats_request.serialize(writer));
            if (this.has_get_latest_stats_response)
                writer.writeMessage(4, this.get_latest_stats_response, () => this.get_latest_stats_response.serialize(writer));
            if (this.has_get_user_request)
                writer.writeMessage(5, this.get_user_request, () => this.get_user_request.serialize(writer));
            if (this.has_get_user_response)
                writer.writeMessage(6, this.get_user_response, () => this.get_user_response.serialize(writer));
            if (this.has_update_discord_user_request)
                writer.writeMessage(7, this.update_discord_user_request, () => this.update_discord_user_request.serialize(writer));
            if (this.has_update_discord_user_response)
                writer.writeMessage(8, this.update_discord_user_response, () => this.update_discord_user_response.serialize(writer));
            if (this.has_get_courses_teasers_request)
                writer.writeMessage(9, this.get_courses_teasers_request, () => this.get_courses_teasers_request.serialize(writer));
            if (this.has_get_courses_teasers_response)
                writer.writeMessage(10, this.get_courses_teasers_response, () => this.get_courses_teasers_response.serialize(writer));
            if (this.has_get_course_request)
                writer.writeMessage(11, this.get_course_request, () => this.get_course_request.serialize(writer));
            if (this.has_get_course_response)
                writer.writeMessage(12, this.get_course_response, () => this.get_course_response.serialize(writer));
            if (this.has_get_page_request)
                writer.writeMessage(13, this.get_page_request, () => this.get_page_request.serialize(writer));
            if (this.has_get_page_response)
                writer.writeMessage(14, this.get_page_response, () => this.get_page_response.serialize(writer));
            if (this.has_get_posts_teasers_request)
                writer.writeMessage(15, this.get_posts_teasers_request, () => this.get_posts_teasers_request.serialize(writer));
            if (this.has_get_posts_teasers_response)
                writer.writeMessage(16, this.get_posts_teasers_response, () => this.get_posts_teasers_response.serialize(writer));
            if (this.has_get_post_request)
                writer.writeMessage(17, this.get_post_request, () => this.get_post_request.serialize(writer));
            if (this.has_get_post_response)
                writer.writeMessage(18, this.get_post_response, () => this.get_post_response.serialize(writer));
            if (this.has_get_categories_teasers_request)
                writer.writeMessage(19, this.get_categories_teasers_request, () => this.get_categories_teasers_request.serialize(writer));
            if (this.has_get_categories_teasers_response)
                writer.writeMessage(20, this.get_categories_teasers_response, () => this.get_categories_teasers_response.serialize(writer));
            if (this.has_get_category_request)
                writer.writeMessage(21, this.get_category_request, () => this.get_category_request.serialize(writer));
            if (this.has_get_category_response)
                writer.writeMessage(22, this.get_category_response, () => this.get_category_response.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Wrapper {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Wrapper();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.api_token = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.error_response, () => message.error_response = Error.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.get_latest_stats_request, () => message.get_latest_stats_request = dependency_1.messages.GetLatestStatsRequest.deserialize(reader));
                        break;
                    case 4:
                        reader.readMessage(message.get_latest_stats_response, () => message.get_latest_stats_response = dependency_1.messages.GetLatestStatsResponse.deserialize(reader));
                        break;
                    case 5:
                        reader.readMessage(message.get_user_request, () => message.get_user_request = dependency_2.messages.GetUserRequest.deserialize(reader));
                        break;
                    case 6:
                        reader.readMessage(message.get_user_response, () => message.get_user_response = dependency_2.messages.GetUserResponse.deserialize(reader));
                        break;
                    case 7:
                        reader.readMessage(message.update_discord_user_request, () => message.update_discord_user_request = dependency_2.messages.UpdateDiscordUserRequest.deserialize(reader));
                        break;
                    case 8:
                        reader.readMessage(message.update_discord_user_response, () => message.update_discord_user_response = dependency_2.messages.UpdateDiscordUserResponse.deserialize(reader));
                        break;
                    case 9:
                        reader.readMessage(message.get_courses_teasers_request, () => message.get_courses_teasers_request = dependency_3.messages.GetCoursesTeasersRequest.deserialize(reader));
                        break;
                    case 10:
                        reader.readMessage(message.get_courses_teasers_response, () => message.get_courses_teasers_response = dependency_3.messages.GetCoursesTeasersResponse.deserialize(reader));
                        break;
                    case 11:
                        reader.readMessage(message.get_course_request, () => message.get_course_request = dependency_3.messages.GetCourseRequest.deserialize(reader));
                        break;
                    case 12:
                        reader.readMessage(message.get_course_response, () => message.get_course_response = dependency_3.messages.GetCourseResponse.deserialize(reader));
                        break;
                    case 13:
                        reader.readMessage(message.get_page_request, () => message.get_page_request = dependency_4.messages.GetPageRequest.deserialize(reader));
                        break;
                    case 14:
                        reader.readMessage(message.get_page_response, () => message.get_page_response = dependency_4.messages.GetPageResponse.deserialize(reader));
                        break;
                    case 15:
                        reader.readMessage(message.get_posts_teasers_request, () => message.get_posts_teasers_request = dependency_4.messages.GetPostsTeasersRequest.deserialize(reader));
                        break;
                    case 16:
                        reader.readMessage(message.get_posts_teasers_response, () => message.get_posts_teasers_response = dependency_4.messages.GetPostsTeasersResponse.deserialize(reader));
                        break;
                    case 17:
                        reader.readMessage(message.get_post_request, () => message.get_post_request = dependency_4.messages.GetPostRequest.deserialize(reader));
                        break;
                    case 18:
                        reader.readMessage(message.get_post_response, () => message.get_post_response = dependency_4.messages.GetPostResponse.deserialize(reader));
                        break;
                    case 19:
                        reader.readMessage(message.get_categories_teasers_request, () => message.get_categories_teasers_request = dependency_4.messages.GetCategoriesTeasersRequest.deserialize(reader));
                        break;
                    case 20:
                        reader.readMessage(message.get_categories_teasers_response, () => message.get_categories_teasers_response = dependency_4.messages.GetCategoriesTeasersResponse.deserialize(reader));
                        break;
                    case 21:
                        reader.readMessage(message.get_category_request, () => message.get_category_request = dependency_4.messages.GetCategoryRequest.deserialize(reader));
                        break;
                    case 22:
                        reader.readMessage(message.get_category_response, () => message.get_category_response = dependency_4.messages.GetCategoryResponse.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Wrapper {
            return Wrapper.deserialize(bytes);
        }
    }
}
