/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.4
 * source: wrapper.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./stats/api";
import * as pb_1 from "google-protobuf";
export namespace messages {
    export class Wrapper extends pb_1.Message {
        #one_of_decls: number[][] = [[2, 3]];
        constructor(data?: any[] | ({
            api_token?: string;
        } & (({
            latest_stats_request?: dependency_1.messages.LatestStatsRequest;
            latest_stats_response?: never;
        } | {
            latest_stats_request?: never;
            latest_stats_response?: dependency_1.messages.LatestStatsResponse;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("api_token" in data && data.api_token != undefined) {
                    this.api_token = data.api_token;
                }
                if ("latest_stats_request" in data && data.latest_stats_request != undefined) {
                    this.latest_stats_request = data.latest_stats_request;
                }
                if ("latest_stats_response" in data && data.latest_stats_response != undefined) {
                    this.latest_stats_response = data.latest_stats_response;
                }
            }
        }
        get api_token() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set api_token(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get latest_stats_request() {
            return pb_1.Message.getWrapperField(this, dependency_1.messages.LatestStatsRequest, 2) as dependency_1.messages.LatestStatsRequest;
        }
        set latest_stats_request(value: dependency_1.messages.LatestStatsRequest) {
            pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
        }
        get has_latest_stats_request() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get latest_stats_response() {
            return pb_1.Message.getWrapperField(this, dependency_1.messages.LatestStatsResponse, 3) as dependency_1.messages.LatestStatsResponse;
        }
        set latest_stats_response(value: dependency_1.messages.LatestStatsResponse) {
            pb_1.Message.setOneofWrapperField(this, 3, this.#one_of_decls[0], value);
        }
        get has_latest_stats_response() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get message() {
            const cases: {
                [index: number]: "none" | "latest_stats_request" | "latest_stats_response";
            } = {
                0: "none",
                2: "latest_stats_request",
                3: "latest_stats_response"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2, 3])];
        }
        static fromObject(data: {
            api_token?: string;
            latest_stats_request?: ReturnType<typeof dependency_1.messages.LatestStatsRequest.prototype.toObject>;
            latest_stats_response?: ReturnType<typeof dependency_1.messages.LatestStatsResponse.prototype.toObject>;
        }): Wrapper {
            const message = new Wrapper({});
            if (data.api_token != null) {
                message.api_token = data.api_token;
            }
            if (data.latest_stats_request != null) {
                message.latest_stats_request = dependency_1.messages.LatestStatsRequest.fromObject(data.latest_stats_request);
            }
            if (data.latest_stats_response != null) {
                message.latest_stats_response = dependency_1.messages.LatestStatsResponse.fromObject(data.latest_stats_response);
            }
            return message;
        }
        toObject() {
            const data: {
                api_token?: string;
                latest_stats_request?: ReturnType<typeof dependency_1.messages.LatestStatsRequest.prototype.toObject>;
                latest_stats_response?: ReturnType<typeof dependency_1.messages.LatestStatsResponse.prototype.toObject>;
            } = {};
            if (this.api_token != null) {
                data.api_token = this.api_token;
            }
            if (this.latest_stats_request != null) {
                data.latest_stats_request = this.latest_stats_request.toObject();
            }
            if (this.latest_stats_response != null) {
                data.latest_stats_response = this.latest_stats_response.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.api_token.length)
                writer.writeString(1, this.api_token);
            if (this.has_latest_stats_request)
                writer.writeMessage(2, this.latest_stats_request, () => this.latest_stats_request.serialize(writer));
            if (this.has_latest_stats_response)
                writer.writeMessage(3, this.latest_stats_response, () => this.latest_stats_response.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Wrapper {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Wrapper();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.api_token = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message.latest_stats_request, () => message.latest_stats_request = dependency_1.messages.LatestStatsRequest.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.latest_stats_response, () => message.latest_stats_response = dependency_1.messages.LatestStatsResponse.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Wrapper {
            return Wrapper.deserialize(bytes);
        }
    }
}
